### ISSUE TITLE
[功能建议] 指定某些组件，复制并开启一个带vue-config的新项目

### ISSUE THREAD

**Issue by luckymore** [zhanghao-zhoushan/create-project-template#1]
比如我们内部搞组件化，写了几十个业务组件都放到components/*底下了，然后有个新项目只用其中四个。
使用`create-project-template ...` 直接创建一个包含指定这四个组件的新项目。

**Comment by zxs-1024** [comment]
老哥，抱歉，没注意看这个 Issues，可以提供一个参数，为需要创建组件的 ['Button', 'Input', 'Alert', 'Loading'] 数组，如果没有传入，拷贝全部，如果传入根据数组的组件名匹配文件夹名进行拷贝。
